on: workflow_dispatch

name: Deploy Anvil

jobs:
  deploy-anvil:
    name: Deploy Anvil
    runs-on: ubuntu-latest
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Ngrok Tunnel
        id: ngrok 
        uses: luisboto/ngrok-tunnel-action@v0.1.7.2
        with:
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          port: 8545
          tunnel_type: http
          timeout: 6
      - name: Print Ngrok URL
        run: echo ${{ steps.ngrok.outputs.tunnel-url }}
        shell: bash
      - name: Run anvil
        run: anvil
        shell: bash